build: Pull modules at once
To prevent lock issues on parallel builds:

  error: could not lock config file .git/config: File exists

Bug: https://jira.iotivity.org/browse/LITE-4
Change-Id: I2f4ee3ddacfa1dfffaf407e0cf99af4e178bc8dc
Origin: https://gerrit.iotivity.org/gerrit/#/c/25183/
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/25189
Tested-by: IoTivity Jenkins <jenkins-daemon@iotivity.org>
Reviewed-by: Kishen Maloor <kishen.maloor@intel.com>
(cherry picked from commit 2670d707d377e253d67a1f18a668e6663fa13c2a)