Update patch set 31
Patch Set 31:

(3 comments)

You have a bunch of build failures.

14:35:06 gcc -o CertificationApp ../../apps/device_builder_server.c ../../apps/CertificationApp.c libiotivity-constrained-client-server.a -DOC_CLIENT -DOC_SERVER  -fPIC -fno-asynchronous-unwind-tables -fno-omit-frame-pointer -ffreestanding -Os -fno-stack-protector -ffunction-sections -fdata-sections -fno-reorder-functions -fno-defer-pop -fno-strict-overflow -I./ -I../../include/ -I../../ -std=gnu99 -Wall -Wextra -Werror -pedantic  -Wl,--gc-sections -I../../deps/mbedtls/include -D__OC_RANDOM  -DOC_PKI -DOC_DYNAMIC_ALLOCATION -DOC_SECURITY -DOC_IPV4 -DOC_TCP -I../../api/cloud -lm -pthread -lrt
14:35:07 /tmp/cc4V73V1.o: In function `cloud_logout_cb':
14:35:07 CertificationApp.c:(.text.cloud_logout_cb+0x58): undefined reference to `oc_cloud_get_token_expiry'
14:35:07 /tmp/cc4V73V1.o: In function `cloud_deregister_cb':
14:35:07 CertificationApp.c:(.text.cloud_deregister_cb+0x58): undefined reference to `oc_cloud_get_token_expiry'
14:35:07 /tmp/cc4V73V1.o: In function `cloud_refresh_token_cb':
14:35:07 CertificationApp.c:(.text.cloud_refresh_token_cb+0x58): undefined reference to `oc_cloud_get_token_expiry'
14:35:07 /tmp/cc4V73V1.o: In function `cloud_register_cb':
14:35:07 CertificationApp.c:(.text.cloud_register_cb+0x58): undefined reference to `oc_cloud_get_token_expiry'
14:35:07 /tmp/cc4V73V1.o: In function `cloud_login_cb':
14:35:07 CertificationApp.c:(.text.cloud_login_cb+0x58): undefined reference to `oc_cloud_get_token_expiry'
14:35:07 /tmp/cc4V73V1.o: In function `selectMenu':
14:35:07 CertificationApp.c:(.text.selectMenu+0x319): undefined reference to `oc_cloud_publish_resources'
14:35:07 CertificationApp.c:(.text.selectMenu+0x252d): undefined reference to `oc_cloud_get_context'
14:35:07 CertificationApp.c:(.text.selectMenu+0x2556): undefined reference to `oc_cloud_register'
14:35:07 CertificationApp.c:(.text.selectMenu+0x2586): undefined reference to `oc_cloud_get_context'
14:35:07 CertificationApp.c:(.text.selectMenu+0x25af): undefined reference to `oc_cloud_login'
14:35:07 CertificationApp.c:(.text.selectMenu+0x25df): undefined reference to `oc_cloud_get_context'
14:35:07 CertificationApp.c:(.text.selectMenu+0x2608): undefined reference to `oc_cloud_logout'
14:35:07 CertificationApp.c:(.text.selectMenu+0x2638): undefined reference to `oc_cloud_get_context'
14:35:07 CertificationApp.c:(.text.selectMenu+0x2661): undefined reference to `oc_cloud_deregister'
14:35:07 CertificationApp.c:(.text.selectMenu+0x268a): undefined reference to `oc_cloud_get_context'
14:35:07 CertificationApp.c:(.text.selectMenu+0x26b3): undefined reference to `oc_cloud_refresh_token'
14:35:07 collect2: error: ld returned 1 exit status


You will likely need to surround some of the code with an ifdef oc_cloud so it will build even when CLOUD=0

Patch-set: 31
Label: Verified=0