Update patch set 9
Patch Set 9:

Well I suspect the current port is not correct, look at:


ipadapter.c:85:55: error: 'OC_MAX_SESSION_EVENT_CBS' undeclared here (not in a function)
 OC_MEMB(oc_session_event_cb_s, oc_session_event_cb_t, OC_MAX_SESSION_EVENT_CBS);

This is only defined in linux headers...

I am not sure we're building this code, now :/

Patch-set: 9