Declare void parameter for RIOT
This is partially reverting:
 "Bring RIOT OS port up-to-date with RIOT OS upstream"

This reverts commit 0ed0f4425cffdd84317998efa8fe19eef561c2fa.

Without this change RIOT will fail to build:
  port/riot/abort.c:5:1:\
  error: old-style function definition [-Werror=old-style-definition]

Change-Id: Ie6b838452412c844503a004656b7aac7b20e5d55
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>