Catch exceptions thrown from SWIG code
Previously, unprovisioned clients had some valid OCStatus code.
Some recent change in the underlying code can cause SWIG to
generate an exception when getting an OCStatus enum since the
integer is not in the OC_STATUS enum in oc_ri.h

This change catches the exception and prints an error instead
of crashing.  This also prevents the android apps from
crashing.

 Sent PUT request
 -----------------
 PUT light:
 FATAL EXCEPTION: Thread-4
 Process: org.iotivity.simpleclient, PID: 14323
 java.lang.IllegalArgumentException: No enum class org.iotivity.OCStatus with value 163
   at org.iotivity.OCStatus.swigToEnum(OCStatus.java:47)
   at org.iotivity.OCClientResponse.getCode(OCClientResponse.java:61)
   at org.iotivity.simpleclient.PutLightResponseHandler.handler(PutLightResponseHandler.java:25)

Change-Id: I296826082ba0c68a9bb665a4db347f152b9f5a09
Signed-off-by: Larry Sachs <larry.j.sachs@intel.com>